<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="ARBACNBK148"><DocLocation><![CDATA[C:\Automatización\COTA\Alta Avería]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Alta Avería]]></DName>
<Res><![CDATA[Res14]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Códigos de Falta]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:51]]></Time>
<TimeTick>1405365231</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:51]]></Time>
<TimeTick>1405365231</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:53]]></Time>
<TimeTick>1405365233</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:53]]></Time>
<TimeTick>1405365233</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:55]]></Time>
<TimeTick>1405365235</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:55]]></Time>
<TimeTick>1405365235</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:57]]></Time>
<TimeTick>1405365237</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:57]]></Time>
<TimeTick>1405365237</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="21" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:58]]></Time>
<TimeTick>1405365238</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:13:58]]></Time>
<TimeTick>1405365238</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="25" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:00]]></Time>
<TimeTick>1405365240</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:00]]></Time>
<TimeTick>1405365240</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:02]]></Time>
<TimeTick>1405365242</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:02]]></Time>
<TimeTick>1405365242</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:04]]></Time>
<TimeTick>1405365244</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:04]]></Time>
<TimeTick>1405365244</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="37" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:06]]></Time>
<TimeTick>1405365246</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:06]]></Time>
<TimeTick>1405365246</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="41" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:08]]></Time>
<TimeTick>1405365248</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:08]]></Time>
<TimeTick>1405365248</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="45" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:10]]></Time>
<TimeTick>1405365250</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:10]]></Time>
<TimeTick>1405365250</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="49" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:11]]></Time>
<TimeTick>1405365251</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:12]]></Time>
<TimeTick>1405365252</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="53" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:13]]></Time>
<TimeTick>1405365253</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:13]]></Time>
<TimeTick>1405365253</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="57" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:18]]></Time>
<TimeTick>1405365258</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="59" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:19]]></Time>
<TimeTick>1405365259</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="61" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:20]]></Time>
<TimeTick>1405365260</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="63" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:21]]></Time>
<TimeTick>1405365261</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="65" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:34]]></Time>
<TimeTick>1405365274</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="67" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:34]]></Time>
<TimeTick>1405365274</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="69" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:37]]></Time>
<TimeTick>1405365277</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="71" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:37]]></Time>
<TimeTick>1405365277</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="73" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:40]]></Time>
<TimeTick>1405365280</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:40]]></Time>
<TimeTick>1405365280</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="77" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:41]]></Time>
<TimeTick>1405365281</TimeTick>
<NodeArgs eType="General" icon="7" nRep="78" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action1" SourceLine="32" >
<Disp><![CDATA[Códigos de Falta]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14/07/2014 - 16:13:51" eTime="14/07/2014 - 16:14:41" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14/07/2014 - 16:14:41]]></Time>
<TimeTick>1405365281</TimeTick>
<NodeArgs eType="General" icon="8" nRep="80" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14/07/2014 - 16:13:30" eTime="14/07/2014 - 16:14:41" passed="0" failed="0" warnings="0" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test Alta Avería Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>