<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="ARBACNBK148"><DocLocation><![CDATA[C:\Automatización\COTA\Alta Cliente]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Alta Cliente]]></DName>
<Res><![CDATA[Res13]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Action1 [LogIn]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[PULIST.EXE]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[16/07/2014 - 12:03:13]]></Time>
<TimeTick>1405522993</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:03:13]]></Time>
<TimeTick>1405522993</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" Source="Action1 [LogIn]" SourceLine="4" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" Source="Action1 [LogIn]" SourceLine="4" >
<Disp><![CDATA[PULIST.EXE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Rul148q]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[16/07/2014 - 12:03:34]]></Time>
<TimeTick>1405523014</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[&No.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:03:34]]></Time>
<TimeTick>1405523014</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" status="Warning" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[&No.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[&No]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&No" object's parent "Rul148q" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[16/07/2014 - 12:03:34]]></Time>
<TimeTick>1405523014</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Rul148q]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = Rul148q<br>Native Class = #32770<br>is owned window = 0<br>is child window = 0<br>]]></Details>
<Time><![CDATA[16/07/2014 - 12:03:34]]></Time>
<TimeTick>1405523014</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" status="Warning" nType="Parent description" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[Rul148q]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="21" status="Failed" nType="Run Error" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[&No]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="19" status="Failed" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[Rul148q]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;&amp;No&quot; object's parent &quot;Rul148q&quot; (class Dialog). Verify that parent properties match an object currently displayed in your application.<BR>Line (6): &quot;Dialog(&quot;Rul148q&quot;).WinButton(&quot;&amp;No&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[16/07/2014 - 12:03:34]]></Time>
<TimeTick>1405523014</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" status="Failed" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Rul148q]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:34]]></Time>
<TimeTick>1405523074</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[&No.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:34]]></Time>
<TimeTick>1405523074</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[&No.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[Rul148q]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Bienvenido]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:54]]></Time>
<TimeTick>1405523094</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Bienvenido.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[338, 154]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:54]]></Time>
<TimeTick>1405523094</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="29" Source="Action1 [LogIn]" SourceLine="6" >
<Disp><![CDATA[Bienvenido.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Usuario:.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:54]]></Time>
<TimeTick>1405523094</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="31" Source="Action1 [LogIn]" SourceLine="7" >
<Disp><![CDATA[Usuario:.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Usuario:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["cgc014"]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:55]]></Time>
<TimeTick>1405523095</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" Source="Action1 [LogIn]" SourceLine="8" >
<Disp><![CDATA[Usuario:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Usuario:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:55]]></Time>
<TimeTick>1405523095</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="35" Source="Action1 [LogIn]" SourceLine="9" >
<Disp><![CDATA[Usuario:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Password:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["BD2VWapm"]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:57]]></Time>
<TimeTick>1405523097</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="37" Source="Action1 [LogIn]" SourceLine="10" >
<Disp><![CDATA[Password:.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="28" Source="Action1 [LogIn]" SourceLine="6" >
<Disp><![CDATA[Bienvenido]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[LogIn]]></Obj>
<Details ><![CDATA[Funcionó]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:58]]></Time>
<TimeTick>1405523098</TimeTick>
<NodeArgs eType="User" icon="12" nRep="38" status="Passed" Source="Action1 [LogIn]" SourceLine="12" >
<Disp><![CDATA[LogIn]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf8.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Bienvenido]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:58]]></Time>
<TimeTick>1405523098</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Con&firmar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:04:58]]></Time>
<TimeTick>1405523098</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" Source="Action1 [LogIn]" SourceLine="13" >
<Disp><![CDATA[Con&firmar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="40" Source="Action1 [LogIn]" SourceLine="13" >
<Disp><![CDATA[Bienvenido]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="16/07/2014 - 12:03:08" eTime="16/07/2014 - 12:04:58" passed="1" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Failed" >
<Disp><![CDATA[Action1 [LogIn] Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:05:30]]></Time>
<TimeTick>1405523130</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Menú Principal.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[238, 121]]></Details>
<Time><![CDATA[16/07/2014 - 12:05:30]]></Time>
<TimeTick>1405523130</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" status="Warning" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Menú Principal.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Menú Principal" (of class Window). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[16/07/2014 - 12:05:30]]></Time>
<TimeTick>1405523130</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>regexpwndtitle = Menú Principal<br>regexpwndclass = AE Runtime<br>is owned window = 0<br>is child window = 0<br>]]></Details>
<Time><![CDATA[16/07/2014 - 12:05:30]]></Time>
<TimeTick>1405523130</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" status="Warning" nType="Description" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="47" status="Failed" nType="Run Error" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="45" status="Failed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Menú Principal&quot; (of class Window). Verify that this object's properties match an object currently displayed in your application.<BR>Line (8): &quot;Window(&quot;Menú Principal&quot;).Move 238,121&quot;. ]]></Details>
<Time><![CDATA[16/07/2014 - 12:05:30]]></Time>
<TimeTick>1405523130</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="49" status="Failed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:36]]></Time>
<TimeTick>1405523256</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Menú Principal.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[238, 121]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:36]]></Time>
<TimeTick>1405523256</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="52" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Menú Principal.Move]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="51" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[MenuPpal]]></Obj>
<Details ><![CDATA[Error]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:37]]></Time>
<TimeTick>1405523257</TimeTick>
<NodeArgs eType="User" icon="12" nRep="53" status="Failed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[MenuPpal]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:37]]></Time>
<TimeTick>1405523257</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[A&dministración de Clientes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:37]]></Time>
<TimeTick>1405523257</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="56" Source="Action1" SourceLine="14" >
<Disp><![CDATA[A&dministración de Clientes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="55" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Menú Principal Clientes]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:41]]></Time>
<TimeTick>1405523261</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Menú Principal Clientes.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[266, 141]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:41]]></Time>
<TimeTick>1405523261</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="59" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Menú Principal Clientes.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Alta de C&lientes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:41]]></Time>
<TimeTick>1405523261</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="61" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Alta de C&lientes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="58" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Menú Principal Clientes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:46]]></Time>
<TimeTick>1405523266</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[221, 132]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:46]]></Time>
<TimeTick>1405523266</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="64" Source="Action1" SourceLine="17" >
<Disp><![CDATA[Detalle de Cliente.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Tipo de Cliente:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["DUAL2"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:46]]></Time>
<TimeTick>1405523266</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="66" Source="Action1" SourceLine="19" >
<Disp><![CDATA[Tipo de Cliente:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Tipo de Cliente:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:47]]></Time>
<TimeTick>1405523267</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="68" Source="Action1" SourceLine="20" >
<Disp><![CDATA[Tipo de Cliente:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Apellido:.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:48]]></Time>
<TimeTick>1405523268</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="70" Source="Action1" SourceLine="22" >
<Disp><![CDATA[Apellido:.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Apellido:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Martinez"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:48]]></Time>
<TimeTick>1405523268</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="72" Source="Action1" SourceLine="23" >
<Disp><![CDATA[Apellido:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Apellido:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:49]]></Time>
<TimeTick>1405523269</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="74" Source="Action1" SourceLine="24" >
<Disp><![CDATA[Apellido:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Nombre:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Martin"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:51]]></Time>
<TimeTick>1405523271</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="76" Source="Action1" SourceLine="26" >
<Disp><![CDATA[Nombre:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Masc.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:51]]></Time>
<TimeTick>1405523271</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="78" Source="Action1" SourceLine="28" >
<Disp><![CDATA[Masc.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicHome&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:51]]></Time>
<TimeTick>1405523271</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="80" Source="Action1" SourceLine="31" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicShiftDwn&gt&lt__MicEnd&gt&lt__MicShiftUp&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:52]]></Time>
<TimeTick>1405523272</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="82" Source="Action1" SourceLine="32" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicBack&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:52]]></Time>
<TimeTick>1405523272</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="84" Source="Action1" SourceLine="33" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["1/1/1990"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:52]]></Time>
<TimeTick>1405523272</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="86" Source="Action1" SourceLine="34" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[&?.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:53]]></Time>
<TimeTick>1405523273</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="88" Source="Action1" SourceLine="36" >
<Disp><![CDATA[&?.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="63" Source="Action1" SourceLine="17" >
<Disp><![CDATA[Detalle de Cliente]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Tipo de Documento]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:55]]></Time>
<TimeTick>1405523275</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:55]]></Time>
<TimeTick>1405523275</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="91" Source="Action1" SourceLine="37" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:56]]></Time>
<TimeTick>1405523276</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="93" Source="Action1" SourceLine="38" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:56]]></Time>
<TimeTick>1405523276</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="95" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:56]]></Time>
<TimeTick>1405523276</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="97" Source="Action1" SourceLine="40" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[210, 112]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:56]]></Time>
<TimeTick>1405523276</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="99" Source="Action1" SourceLine="41" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="90" Source="Action1" SourceLine="37" >
<Disp><![CDATA[Tipo de Documento]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[DNI]]></Obj>
<Details ><![CDATA[Error]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:57]]></Time>
<TimeTick>1405523277</TimeTick>
<NodeArgs eType="User" icon="12" nRep="100" status="Failed" Source="Action1" SourceLine="44" >
<Disp><![CDATA[DNI]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Tipo de Documento]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:57]]></Time>
<TimeTick>1405523277</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[&Seleccionar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:57]]></Time>
<TimeTick>1405523277</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="103" Source="Action1" SourceLine="48" >
<Disp><![CDATA[&Seleccionar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="102" Source="Action1" SourceLine="48" >
<Disp><![CDATA[Tipo de Documento]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:58]]></Time>
<TimeTick>1405523278</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Número de Documento:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicDel&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:58]]></Time>
<TimeTick>1405523278</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="106" Source="Action1" SourceLine="50" >
<Disp><![CDATA[Número de Documento:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Número de Documento:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["52526222"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:59]]></Time>
<TimeTick>1405523279</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="108" Source="Action1" SourceLine="51" >
<Disp><![CDATA[Número de Documento:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Número de Documento:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["CONSUMIDOR FINAL"]]></Details>
<Time><![CDATA[16/07/2014 - 12:07:59]]></Time>
<TimeTick>1405523279</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="110" Source="Action1" SourceLine="53" >
<Disp><![CDATA[Número de Documento:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[&?_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:08:00]]></Time>
<TimeTick>1405523280</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="112" Source="Action1" SourceLine="55" >
<Disp><![CDATA[&?_2.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="105" Source="Action1" SourceLine="50" >
<Disp><![CDATA[Detalle de Cliente]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Tipo de Actividad]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 12:08:05]]></Time>
<TimeTick>1405523285</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Tipo de Actividad.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 12:08:05]]></Time>
<TimeTick>1405523285</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="115" Source="Action1" SourceLine="58" >
<Disp><![CDATA[Tipo de Actividad.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[ScrollBar.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[630]]></Details>
<Time><![CDATA[16/07/2014 - 12:08:05]]></Time>
<TimeTick>1405523285</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="117" Source="Action1" SourceLine="59" >
<Disp><![CDATA[ScrollBar.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[16/07/2014 - 12:08:06]]></Time>
<TimeTick>1405523286</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="119" Source="Action1" SourceLine="61" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[ScrollBar.PrevLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 12:08:07]]></Time>
<TimeTick>1405523287</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="121" Source="Action1" SourceLine="73" >
<Disp><![CDATA[ScrollBar.PrevLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">