<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="ARBACNBK148"><DocLocation><![CDATA[C:\Automatización\COTA\Alta Avería]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Alta Avería]]></DName>
<Res><![CDATA[Res20]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[AltaAveria]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Recepcionar Averías]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:15]]></Time>
<TimeTick>1405536855</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Número de Línea:.SetSelection]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0, 0, 2]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:15]]></Time>
<TimeTick>1405536855</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="AltaAveria" SourceLine="15" >
<Disp><![CDATA[Número de Línea:.SetSelection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Número de Línea:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicBack&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:15]]></Time>
<TimeTick>1405536855</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" Source="AltaAveria" SourceLine="16" >
<Disp><![CDATA[Número de Línea:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Número de Línea:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["2622"]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:16]]></Time>
<TimeTick>1405536856</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="AltaAveria" SourceLine="17" >
<Disp><![CDATA[Número de Línea:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Edit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:16]]></Time>
<TimeTick>1405536856</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="15" Source="AltaAveria" SourceLine="18" >
<Disp><![CDATA[Edit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Edit.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:16]]></Time>
<TimeTick>1405536856</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" Source="AltaAveria" SourceLine="19" >
<Disp><![CDATA[Edit.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Edit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["423836"]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:16]]></Time>
<TimeTick>1405536856</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="19" Source="AltaAveria" SourceLine="20" >
<Disp><![CDATA[Edit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[&Buscar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:17]]></Time>
<TimeTick>1405536857</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="21" Source="AltaAveria" SourceLine="21" >
<Disp><![CDATA[&Buscar.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[&?.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:52]]></Time>
<TimeTick>1405536892</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" status="Warning" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[&?.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:52]]></Time>
<TimeTick>1405536892</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>window id = 64<br>Text = &?<br>Native Class = Button<br>]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:52]]></Time>
<TimeTick>1405536892</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" status="Warning" nType="Description" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[PopUp4]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><dl><b><u>Scenario</u>: </b>PopUp4<br><b><u>Defined in</u>: </b>Pop-Ups.qrs<br><b><u>Description</u>: </b><br><b><u>Post-recovery operation</u>: </b>Repeat current step and continue.<br><br><b><u>Activated by trigger</u>:</b><dd><u>Type</u>: Pop-up window<br><u>Contains the caption</u>: Información<br><u>Contains the text</u>: El abonado tiene servicio debloqueo de SPM&Si&Bien&No&Volver</dd><dt><br><b><u>The current test step details</u>:</b><dd><u>Object</u>: WinButton("&?")<br><u>Method</u>: Click<br><u>Arguments</u>: EMPTY<br><u>Result</u>: Object is disabled</dd></dt></dl></div></SPAN>]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:52]]></Time>
<TimeTick>1405536892</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Información]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><b><u>Hierarchical description</u>:</b> Window( is child window := 0, is owned window := 0, regexpwndclass := AE Runtime, regexpwndtitle := Información )</div></SPAN>]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:52]]></Time>
<TimeTick>1405536892</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Button("&Bien").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><b><u>Perform the method</u>:</b> Button("&Bien").Click<br><b>for detected object</b></div></SPAN>]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:52]]></Time>
<TimeTick>1405536892</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Window]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:52]]></Time>
<TimeTick>1405536892</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[&Bien.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:52]]></Time>
<TimeTick>1405536892</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[&Bien.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="30" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[Window]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="28" nType="Object operation" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[Button("&Bien").Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="27" nType="Detected object" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[Información]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Retry]]></Obj>
<Details plainTxt="False" ><![CDATA[Repeat current step and continue.]]></Details>
<Time><![CDATA[16/07/2014 - 15:54:52]]></Time>
<TimeTick>1405536892</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" nType="Step" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[Retry]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="26" nType="PopUp Window" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[PopUp4]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="24" status="Warning" nType="Run Error" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[&?.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:19]]></Time>
<TimeTick>1405536919</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" status="Warning" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[&?.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:19]]></Time>
<TimeTick>1405536919</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>window id = 64<br>Text = &?<br>Native Class = Button<br>]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:19]]></Time>
<TimeTick>1405536919</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" status="Warning" nType="Description" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[PopUp2]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><dl><b><u>Scenario</u>: </b>PopUp2<br><b><u>Defined in</u>: </b>Pop-Ups.qrs<br><b><u>Description</u>: </b><br><b><u>Post-recovery operation</u>: </b>Repeat current step and continue.<br><br><b><u>Activated by trigger</u>:</b><dd><u>Type</u>: Pop-up window<br><u>Contains the caption</u>: Información<br><u>Contains the text</u>: No se encontró una prueba de líneareciente&Si&Bien&No&Volver</dd><dt><br><b><u>The current test step details</u>:</b><dd><u>Object</u>: WinButton("&?")<br><u>Method</u>: Click<br><u>Arguments</u>: EMPTY<br><u>Result</u>: Object is disabled</dd></dt></dl></div></SPAN>]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:19]]></Time>
<TimeTick>1405536919</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Información]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><b><u>Hierarchical description</u>:</b> Window( is child window := 0, is owned window := 0, regexpwndclass := AE Runtime, regexpwndtitle := Información )</div></SPAN>]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:19]]></Time>
<TimeTick>1405536919</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Button("&Bien").Click]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><b><u>Perform the method</u>:</b> Button("&Bien").Click<br><b>for detected object</b></div></SPAN>]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:19]]></Time>
<TimeTick>1405536919</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Window]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:19]]></Time>
<TimeTick>1405536919</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[&Bien.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:19]]></Time>
<TimeTick>1405536919</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[&Bien.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="41" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[Window]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="39" nType="Object operation" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[Button("&Bien").Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="38" nType="Detected object" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[Información]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Retry]]></Obj>
<Details plainTxt="False" ><![CDATA[Repeat current step and continue.]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:20]]></Time>
<TimeTick>1405536920</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="43" nType="Step" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[Retry]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="37" nType="PopUp Window" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[PopUp2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="35" status="Warning" nType="Run Error" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[&?.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:21]]></Time>
<TimeTick>1405536921</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="45" Source="AltaAveria" SourceLine="24" >
<Disp><![CDATA[&?.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" status="Warning" Source="AltaAveria" SourceLine="15" >
<Disp><![CDATA[Recepcionar Averías]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Códigos de Falta]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:22]]></Time>
<TimeTick>1405536922</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:22]]></Time>
<TimeTick>1405536922</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="48" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:23]]></Time>
<TimeTick>1405536923</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="50" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:23]]></Time>
<TimeTick>1405536923</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="52" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:24]]></Time>
<TimeTick>1405536924</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="54" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:25]]></Time>
<TimeTick>1405536925</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="56" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:26]]></Time>
<TimeTick>1405536926</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="58" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:26]]></Time>
<TimeTick>1405536926</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="60" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:27]]></Time>
<TimeTick>1405536927</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="62" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:27]]></Time>
<TimeTick>1405536927</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="64" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:30]]></Time>
<TimeTick>1405536930</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="66" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:31]]></Time>
<TimeTick>1405536931</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="68" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:34]]></Time>
<TimeTick>1405536934</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="70" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:34]]></Time>
<TimeTick>1405536934</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="72" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:35]]></Time>
<TimeTick>1405536935</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="74" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:35]]></Time>
<TimeTick>1405536935</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="76" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:36]]></Time>
<TimeTick>1405536936</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="78" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:37]]></Time>
<TimeTick>1405536937</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="80" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:38]]></Time>
<TimeTick>1405536938</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="82" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:38]]></Time>
<TimeTick>1405536938</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="84" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:39]]></Time>
<TimeTick>1405536939</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="86" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:40]]></Time>
<TimeTick>1405536940</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="88" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:41]]></Time>
<TimeTick>1405536941</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="90" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:41]]></Time>
<TimeTick>1405536941</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="92" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:42]]></Time>
<TimeTick>1405536942</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="94" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:43]]></Time>
<TimeTick>1405536943</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="96" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:44]]></Time>
<TimeTick>1405536944</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="98" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:44]]></Time>
<TimeTick>1405536944</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="100" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:45]]></Time>
<TimeTick>1405536945</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="102" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:45]]></Time>
<TimeTick>1405536945</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="104" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:46]]></Time>
<TimeTick>1405536946</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="106" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:47]]></Time>
<TimeTick>1405536947</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="108" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:48]]></Time>
<TimeTick>1405536948</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="110" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:48]]></Time>
<TimeTick>1405536948</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="112" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:49]]></Time>
<TimeTick>1405536949</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="114" Source="AltaAveria" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[16/07/2014 - 15:55:50]]></Time>
<TimeTick>1405536950</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="116" Source="AltaAveria" SourceLine="27" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">