<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="ARBACNBK148"><DocLocation><![CDATA[C:\Automatización\COTA\Alta Avería]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Alta Avería]]></DName>
<Res><![CDATA[Res7]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Recepcionar Averías]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:37]]></Time>
<TimeTick>1405364437</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Número de Línea:.SetSelection]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0, 0, 2]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:37]]></Time>
<TimeTick>1405364437</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="Action1" SourceLine="20" >
<Disp><![CDATA[Número de Línea:.SetSelection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Número de Línea:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicBack&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:37]]></Time>
<TimeTick>1405364437</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" Source="Action1" SourceLine="21" >
<Disp><![CDATA[Número de Línea:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Número de Línea:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["2622"]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:37]]></Time>
<TimeTick>1405364437</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="Action1" SourceLine="22" >
<Disp><![CDATA[Número de Línea:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Edit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:37]]></Time>
<TimeTick>1405364437</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="15" Source="Action1" SourceLine="23" >
<Disp><![CDATA[Edit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Edit.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:37]]></Time>
<TimeTick>1405364437</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" Source="Action1" SourceLine="24" >
<Disp><![CDATA[Edit.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Edit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["424758"]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:38]]></Time>
<TimeTick>1405364438</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="19" Source="Action1" SourceLine="25" >
<Disp><![CDATA[Edit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[&Buscar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:38]]></Time>
<TimeTick>1405364438</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="21" Source="Action1" SourceLine="26" >
<Disp><![CDATA[&Buscar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action1" SourceLine="20" >
<Disp><![CDATA[Recepcionar Averías]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Información]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:43]]></Time>
<TimeTick>1405364443</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[&Bien.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:43]]></Time>
<TimeTick>1405364443</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="Action1" SourceLine="27" >
<Disp><![CDATA[&Bien.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="23" Source="Action1" SourceLine="27" >
<Disp><![CDATA[Información]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Recepcionar Averías]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:51]]></Time>
<TimeTick>1405364451</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[&?.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:51]]></Time>
<TimeTick>1405364451</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" status="Warning" Source="Action1" SourceLine="28" >
<Disp><![CDATA[&?.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:51]]></Time>
<TimeTick>1405364451</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>window id = 64<br>Text = &?<br>Native Class = Button<br>]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:51]]></Time>
<TimeTick>1405364451</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" status="Warning" nType="Description" Source="Action1" SourceLine="28" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="28" status="Failed" nType="Run Error" Source="Action1" SourceLine="28" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:51]]></Time>
<TimeTick>1405364451</TimeTick>
<NodeArgs eType="General" icon="8" nRep="30" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="26" status="Failed" Source="Action1" SourceLine="28" >
<Disp><![CDATA[Recepcionar Averías]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14/07/2014 - 16:00:37" eTime="14/07/2014 - 16:00:51" passed="0" failed="1" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14/07/2014 - 16:00:51]]></Time>
<TimeTick>1405364451</TimeTick>
<NodeArgs eType="General" icon="9" nRep="32" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14/07/2014 - 16:00:16" eTime="14/07/2014 - 16:00:51" passed="0" failed="1" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Alta Avería Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>