<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="ARBACNBK148"><DocLocation><![CDATA[C:\Automatización\COTA\Alta Avería]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Alta Avería]]></DName>
<Res><![CDATA[Res15]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Códigos de Falta]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:24]]></Time>
<TimeTick>1405365384</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:24]]></Time>
<TimeTick>1405365384</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:26]]></Time>
<TimeTick>1405365386</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:26]]></Time>
<TimeTick>1405365386</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:28]]></Time>
<TimeTick>1405365388</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:28]]></Time>
<TimeTick>1405365388</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:29]]></Time>
<TimeTick>1405365389</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:30]]></Time>
<TimeTick>1405365390</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="21" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:31]]></Time>
<TimeTick>1405365391</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:31]]></Time>
<TimeTick>1405365391</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="25" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:32]]></Time>
<TimeTick>1405365392</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:33]]></Time>
<TimeTick>1405365393</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:34]]></Time>
<TimeTick>1405365394</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:34]]></Time>
<TimeTick>1405365394</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:36]]></Time>
<TimeTick>1405365396</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:36]]></Time>
<TimeTick>1405365396</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="37" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:37]]></Time>
<TimeTick>1405365397</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:37]]></Time>
<TimeTick>1405365397</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="41" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:38]]></Time>
<TimeTick>1405365398</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:38]]></Time>
<TimeTick>1405365398</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="45" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:40]]></Time>
<TimeTick>1405365400</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:40]]></Time>
<TimeTick>1405365400</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="49" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:42]]></Time>
<TimeTick>1405365402</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:42]]></Time>
<TimeTick>1405365402</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="53" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:43]]></Time>
<TimeTick>1405365403</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:43]]></Time>
<TimeTick>1405365403</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="57" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:45]]></Time>
<TimeTick>1405365405</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="59" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:45]]></Time>
<TimeTick>1405365405</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="61" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:46]]></Time>
<TimeTick>1405365406</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="63" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[48, 44]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:46]]></Time>
<TimeTick>1405365406</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="65" Source="Action1" SourceLine="32" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[&Seleccionar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:48]]></Time>
<TimeTick>1405365408</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="67" Source="Action1" SourceLine="36" >
<Disp><![CDATA[&Seleccionar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action1" SourceLine="32" >
<Disp><![CDATA[Códigos de Falta]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Recepcionar Averías]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:48]]></Time>
<TimeTick>1405365408</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Con&firmar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:48]]></Time>
<TimeTick>1405365408</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="70" Source="Action1" SourceLine="42" >
<Disp><![CDATA[Con&firmar.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[&Volver.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:53]]></Time>
<TimeTick>1405365413</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="72" Source="Action1" SourceLine="43" >
<Disp><![CDATA[&Volver.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="69" Source="Action1" SourceLine="42" >
<Disp><![CDATA[Recepcionar Averías]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Menú Principal Averías_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:53]]></Time>
<TimeTick>1405365413</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[&Volver.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:53]]></Time>
<TimeTick>1405365413</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="75" Source="Action1" SourceLine="44" >
<Disp><![CDATA[&Volver.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="74" Source="Action1" SourceLine="44" >
<Disp><![CDATA[Menú Principal Averías_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Menú Principal Averías]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:53]]></Time>
<TimeTick>1405365413</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Menú Principal Averías.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[70, 373]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:53]]></Time>
<TimeTick>1405365413</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="78" Source="Action1" SourceLine="45" >
<Disp><![CDATA[Menú Principal Averías.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[&Volver.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 16:16:53]]></Time>
<TimeTick>1405365413</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="80" Source="Action1" SourceLine="46" >
<Disp><![CDATA[&Volver.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="77" Source="Action1" SourceLine="45" >
<Disp><![CDATA[Menú Principal Averías]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14/07/2014 - 16:16:19" eTime="14/07/2014 - 16:16:53" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="14/07/2014 - 16:15:58" eTime="14/07/2014 - 16:16:53" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test Alta Avería Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>