<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="ARBACNBK148"><DocLocation><![CDATA[C:\Automatización\COTA\Alta Equipo]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Alta Equipo]]></DName>
<Res><![CDATA[Res20]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[AltaEquipo]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Alta/Baja de Equipo]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:32]]></Time>
<TimeTick>1405610552</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Edit.SetSelection]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:32]]></Time>
<TimeTick>1405610552</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Warning" Source="AltaEquipo" SourceLine="41" >
<Disp><![CDATA[Edit.SetSelection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Edit]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Edit" (of class WinEdit). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:32]]></Time>
<TimeTick>1405610552</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Edit]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>window id = 147<br>Native Class = Edit<br>]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:32]]></Time>
<TimeTick>1405610552</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Warning" nType="Description" Source="AltaEquipo" SourceLine="41" >
<Disp><![CDATA[Edit]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Failed" nType="Run Error" Source="AltaEquipo" SourceLine="41" >
<Disp><![CDATA[Edit]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="9" status="Failed" Source="AltaEquipo" SourceLine="41" >
<Disp><![CDATA[Alta/Baja de Equipo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Edit&quot; (of class WinEdit). Verify that this object's properties match an object currently displayed in your application.<BR>Line (42): &quot;Window(&quot;Alta/Baja de Equipo&quot;).WinEdit(&quot;Edit&quot;).SetSelection 0,1&quot;. ]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:33]]></Time>
<TimeTick>1405610553</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Failed" Source="AltaEquipo" SourceLine="41" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Alta/Baja de Equipo]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:40]]></Time>
<TimeTick>1405610560</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:40]]></Time>
<TimeTick>1405610560</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" status="Warning" Source="AltaEquipo" SourceLine="41" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[ScrollBar]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "ScrollBar" (of class WinScrollBar). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:40]]></Time>
<TimeTick>1405610560</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[ScrollBar]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>window id = 146<br>Native Class = ScrollBar<br>]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:40]]></Time>
<TimeTick>1405610560</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" status="Warning" nType="Description" Source="AltaEquipo" SourceLine="41" >
<Disp><![CDATA[ScrollBar]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="18" status="Failed" nType="Run Error" Source="AltaEquipo" SourceLine="41" >
<Disp><![CDATA[ScrollBar]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:40]]></Time>
<TimeTick>1405610560</TimeTick>
<NodeArgs eType="General" icon="8" nRep="20" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="16" status="Failed" Source="AltaEquipo" SourceLine="41" >
<Disp><![CDATA[Alta/Baja de Equipo]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="17/07/2014 - 12:22:11" eTime="17/07/2014 - 12:22:40" passed="0" failed="3" warnings="4" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[AltaEquipo Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[17/07/2014 - 12:22:40]]></Time>
<TimeTick>1405610560</TimeTick>
<NodeArgs eType="General" icon="9" nRep="22" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="17/07/2014 - 12:21:50" eTime="17/07/2014 - 12:22:40" passed="0" failed="3" warnings="4" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Alta Equipo Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>