<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="ARBACNBK148"><DocLocation><![CDATA[C:\Automatización\COTA\Alta Avería]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Alta Avería]]></DName>
<Res><![CDATA[Res5]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[PULIST.EXE]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:27]]></Time>
<TimeTick>1405364187</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:27]]></Time>
<TimeTick>1405364187</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Action1" SourceLine="3" >
<Disp><![CDATA[PULIST.EXE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Rul148q]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:41]]></Time>
<TimeTick>1405364201</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[&No.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:41]]></Time>
<TimeTick>1405364201</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="Action1" SourceLine="4" >
<Disp><![CDATA[&No.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="12" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Rul148q]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Bienvenido]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:46]]></Time>
<TimeTick>1405364206</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Bienvenido.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[282, 132]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:46]]></Time>
<TimeTick>1405364206</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Bienvenido.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Usuario:.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:46]]></Time>
<TimeTick>1405364206</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="6" >
<Disp><![CDATA[Usuario:.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Usuario:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["cgc014"]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:46]]></Time>
<TimeTick>1405364206</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Usuario:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Usuario:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:46]]></Time>
<TimeTick>1405364206</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Usuario:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Password:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["DBD2VWapm"]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:46]]></Time>
<TimeTick>1405364206</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Password:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Con&firmar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 15:56:47]]></Time>
<TimeTick>1405364207</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Con&firmar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Bienvenido]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:09]]></Time>
<TimeTick>1405364229</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Menú Principal.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[286, 146]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:09]]></Time>
<TimeTick>1405364229</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" status="Warning" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Menú Principal.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Menú Principal" (of class Window). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:09]]></Time>
<TimeTick>1405364229</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>regexpwndtitle = Menú Principal<br>regexpwndclass = AE Runtime<br>is owned window = 0<br>is child window = 0<br>]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:09]]></Time>
<TimeTick>1405364229</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="32" status="Warning" nType="Description" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="31" status="Failed" nType="Run Error" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="29" status="Failed" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Menú Principal&quot; (of class Window). Verify that this object's properties match an object currently displayed in your application.<BR>Line (12): &quot;Window(&quot;Menú Principal&quot;).Move 286,146&quot;. ]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:09]]></Time>
<TimeTick>1405364229</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" status="Failed" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:14]]></Time>
<TimeTick>1405364234</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Menú Principal.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[286, 146]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:14]]></Time>
<TimeTick>1405364234</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Menú Principal.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[A&verías.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:14]]></Time>
<TimeTick>1405364234</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="38" Source="Action1" SourceLine="12" >
<Disp><![CDATA[A&verías.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="35" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Menú Principal Averías]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:18]]></Time>
<TimeTick>1405364238</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Menú Principal Averías.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[347, 103]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:18]]></Time>
<TimeTick>1405364238</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" Source="Action1" SourceLine="13" >
<Disp><![CDATA[Menú Principal Averías.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Averías Telefonía &Básica.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:18]]></Time>
<TimeTick>1405364238</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Averías Telefonía &Básica.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="40" Source="Action1" SourceLine="13" >
<Disp><![CDATA[Menú Principal Averías]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Menú Principal Averías_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:19]]></Time>
<TimeTick>1405364239</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Menú Principal Averías_2.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[343, 121]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:19]]></Time>
<TimeTick>1405364239</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="46" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Menú Principal Averías_2.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[R&ecepcionar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:19]]></Time>
<TimeTick>1405364239</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="48" Source="Action1" SourceLine="16" >
<Disp><![CDATA[R&ecepcionar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="45" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Menú Principal Averías_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Recepcionar Averías]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:22]]></Time>
<TimeTick>1405364242</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Recepcionar Averías.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[397, 134]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:22]]></Time>
<TimeTick>1405364242</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" Source="Action1" SourceLine="17" >
<Disp><![CDATA[Recepcionar Averías.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Edit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicShiftDwn&gt&lt__MicBack&gt&lt__MicShiftUp&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:22]]></Time>
<TimeTick>1405364242</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" Source="Action1" SourceLine="19" >
<Disp><![CDATA[Edit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Número de Línea:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["2622"]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:22]]></Time>
<TimeTick>1405364242</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="55" Source="Action1" SourceLine="20" >
<Disp><![CDATA[Número de Línea:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Edit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:23]]></Time>
<TimeTick>1405364243</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="57" Source="Action1" SourceLine="21" >
<Disp><![CDATA[Edit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Edit.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:23]]></Time>
<TimeTick>1405364243</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="59" Source="Action1" SourceLine="22" >
<Disp><![CDATA[Edit.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Edit.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["424758"]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:23]]></Time>
<TimeTick>1405364243</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="61" Source="Action1" SourceLine="23" >
<Disp><![CDATA[Edit.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[&Buscar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:23]]></Time>
<TimeTick>1405364243</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="63" Source="Action1" SourceLine="24" >
<Disp><![CDATA[&Buscar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="50" Source="Action1" SourceLine="17" >
<Disp><![CDATA[Recepcionar Averías]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Información]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:27]]></Time>
<TimeTick>1405364247</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[&Bien.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:27]]></Time>
<TimeTick>1405364247</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="66" Source="Action1" SourceLine="25" >
<Disp><![CDATA[&Bien.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="65" Source="Action1" SourceLine="25" >
<Disp><![CDATA[Información]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Recepcionar Averías]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:37]]></Time>
<TimeTick>1405364257</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[&?.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:37]]></Time>
<TimeTick>1405364257</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="69" status="Warning" Source="Action1" SourceLine="26" >
<Disp><![CDATA[&?.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:37]]></Time>
<TimeTick>1405364257</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>window id = 64<br>Text = &?<br>Native Class = Button<br>]]></Details>
<Time><![CDATA[14/07/2014 - 15:57:37]]></Time>
<TimeTick>1405364257</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="71" status="Warning" nType="Description" Source="Action1" SourceLine="26" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="70" status="Failed" nType="Run Error" Source="Action1" SourceLine="26" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14/07/2014 - 15:58:06]]></Time>
<TimeTick>1405364286</TimeTick>
<NodeArgs eType="General" icon="11" nRep="72" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="68" status="Failed" Source="Action1" SourceLine="26" >
<Disp><![CDATA[Recepcionar Averías]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14/07/2014 - 15:56:24" eTime="14/07/2014 - 15:58:06" passed="0" failed="3" warnings="4" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Alta Avería Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14/07/2014 - 15:58:06]]></Time>
<TimeTick>1405364286</TimeTick>
<NodeArgs eType="General" icon="12" nRep="75" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14/07/2014 - 15:56:03" eTime="14/07/2014 - 15:58:06" passed="0" failed="3" warnings="4" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Alta Avería Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>