<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="ARBACNBK148"><DocLocation><![CDATA[C:\Automatización\COTA\Alta Cliente]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Alta Cliente]]></DName>
<Res><![CDATA[Res11]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Action1 [LogIn]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[PULIST.EXE]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[16/07/2014 - 11:32:38]]></Time>
<TimeTick>1405521158</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:32:38]]></Time>
<TimeTick>1405521158</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" Source="Action1 [LogIn]" SourceLine="4" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" Source="Action1 [LogIn]" SourceLine="4" >
<Disp><![CDATA[PULIST.EXE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Rul148q]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[16/07/2014 - 11:32:59]]></Time>
<TimeTick>1405521179</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[&No.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:32:59]]></Time>
<TimeTick>1405521179</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" status="Warning" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[&No.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[&No]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&No" object's parent "Rul148q" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[16/07/2014 - 11:32:59]]></Time>
<TimeTick>1405521179</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Rul148q]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = Rul148q<br>Native Class = #32770<br>is owned window = 0<br>is child window = 0<br>]]></Details>
<Time><![CDATA[16/07/2014 - 11:32:59]]></Time>
<TimeTick>1405521179</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" status="Warning" nType="Parent description" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[Rul148q]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="21" status="Failed" nType="Run Error" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[&No]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="19" status="Failed" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[Rul148q]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;&amp;No&quot; object's parent &quot;Rul148q&quot; (class Dialog). Verify that parent properties match an object currently displayed in your application.<BR>Line (6): &quot;Dialog(&quot;Rul148q&quot;).WinButton(&quot;&amp;No&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[16/07/2014 - 11:32:59]]></Time>
<TimeTick>1405521179</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" status="Failed" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Rul148q]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:08]]></Time>
<TimeTick>1405521188</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[&No.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:08]]></Time>
<TimeTick>1405521188</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[&No.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="Action1 [LogIn]" SourceLine="5" >
<Disp><![CDATA[Rul148q]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Bienvenido]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:18]]></Time>
<TimeTick>1405521198</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Bienvenido.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[338, 154]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:18]]></Time>
<TimeTick>1405521198</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="29" Source="Action1 [LogIn]" SourceLine="6" >
<Disp><![CDATA[Bienvenido.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Usuario:.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:19]]></Time>
<TimeTick>1405521199</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="31" Source="Action1 [LogIn]" SourceLine="7" >
<Disp><![CDATA[Usuario:.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Usuario:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["cgc014"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:19]]></Time>
<TimeTick>1405521199</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" Source="Action1 [LogIn]" SourceLine="8" >
<Disp><![CDATA[Usuario:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Usuario:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:20]]></Time>
<TimeTick>1405521200</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="35" Source="Action1 [LogIn]" SourceLine="9" >
<Disp><![CDATA[Usuario:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Password:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["BD2VWapm"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:21]]></Time>
<TimeTick>1405521201</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="37" Source="Action1 [LogIn]" SourceLine="10" >
<Disp><![CDATA[Password:.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="28" Source="Action1 [LogIn]" SourceLine="6" >
<Disp><![CDATA[Bienvenido]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[LogIn]]></Obj>
<Details ><![CDATA[Funcionó]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:21]]></Time>
<TimeTick>1405521201</TimeTick>
<NodeArgs eType="User" icon="12" nRep="38" status="Passed" Source="Action1 [LogIn]" SourceLine="12" >
<Disp><![CDATA[LogIn]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Bienvenido]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:22]]></Time>
<TimeTick>1405521202</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Con&firmar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:22]]></Time>
<TimeTick>1405521202</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" Source="Action1 [LogIn]" SourceLine="13" >
<Disp><![CDATA[Con&firmar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="40" Source="Action1 [LogIn]" SourceLine="13" >
<Disp><![CDATA[Bienvenido]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="16/07/2014 - 11:32:36" eTime="16/07/2014 - 11:33:22" passed="1" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Failed" >
<Disp><![CDATA[Action1 [LogIn] Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:32]]></Time>
<TimeTick>1405521212</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Menú Principal.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[238, 121]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:32]]></Time>
<TimeTick>1405521212</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Menú Principal.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[A&dministración de Clientes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:33]]></Time>
<TimeTick>1405521213</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="47" Source="Action1" SourceLine="7" >
<Disp><![CDATA[A&dministración de Clientes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="44" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Menú Principal Clientes]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:35]]></Time>
<TimeTick>1405521215</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Menú Principal Clientes.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[266, 141]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:35]]></Time>
<TimeTick>1405521215</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Menú Principal Clientes.Move]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="49" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Menú Principal Clientes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot open file: 'C:\Automatización\COTA\Capturas\MenuPpal.png'.<BR>Line (10): &quot;Reporter.ReportEvent micPass, &quot;MenuPpal&quot;, &quot;Funciona&quot;, &quot;C:\Automatización\COTA\Capturas\MenuPpal.png&quot;&quot;. ]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:35]]></Time>
<TimeTick>1405521215</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="51" status="Failed" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Menú Principal Clientes]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:44]]></Time>
<TimeTick>1405521224</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Alta de C&lientes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:44]]></Time>
<TimeTick>1405521224</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Alta de C&lientes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="53" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Menú Principal Clientes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:48]]></Time>
<TimeTick>1405521228</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[221, 132]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:48]]></Time>
<TimeTick>1405521228</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Detalle de Cliente.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Tipo de Cliente:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["DUAL2"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:48]]></Time>
<TimeTick>1405521228</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="59" Source="Action1" SourceLine="13" >
<Disp><![CDATA[Tipo de Cliente:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Tipo de Cliente:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:49]]></Time>
<TimeTick>1405521229</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="61" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Tipo de Cliente:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Apellido:.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:50]]></Time>
<TimeTick>1405521230</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="63" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Apellido:.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Apellido:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Martinez"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:50]]></Time>
<TimeTick>1405521230</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="65" Source="Action1" SourceLine="17" >
<Disp><![CDATA[Apellido:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Apellido:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:50]]></Time>
<TimeTick>1405521230</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="67" Source="Action1" SourceLine="18" >
<Disp><![CDATA[Apellido:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Nombre:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Martin"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:51]]></Time>
<TimeTick>1405521231</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" Source="Action1" SourceLine="20" >
<Disp><![CDATA[Nombre:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Masc.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:52]]></Time>
<TimeTick>1405521232</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="71" Source="Action1" SourceLine="22" >
<Disp><![CDATA[Masc.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicHome&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:52]]></Time>
<TimeTick>1405521232</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="73" Source="Action1" SourceLine="25" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicShiftDwn&gt&lt__MicEnd&gt&lt__MicShiftUp&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:52]]></Time>
<TimeTick>1405521232</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="75" Source="Action1" SourceLine="26" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicBack&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:52]]></Time>
<TimeTick>1405521232</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="77" Source="Action1" SourceLine="27" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["1/1/1990"]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:52]]></Time>
<TimeTick>1405521232</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="79" Source="Action1" SourceLine="28" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[&?.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:53]]></Time>
<TimeTick>1405521233</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="81" Source="Action1" SourceLine="30" >
<Disp><![CDATA[&?.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="56" Source="Action1" SourceLine="11" >
<Disp><![CDATA[Detalle de Cliente]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Tipo de Documento]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:55]]></Time>
<TimeTick>1405521235</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:55]]></Time>
<TimeTick>1405521235</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="84" Source="Action1" SourceLine="31" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:55]]></Time>
<TimeTick>1405521235</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="86" Source="Action1" SourceLine="32" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:55]]></Time>
<TimeTick>1405521235</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="88" Source="Action1" SourceLine="33" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:55]]></Time>
<TimeTick>1405521235</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="90" Source="Action1" SourceLine="34" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[210, 112]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:55]]></Time>
<TimeTick>1405521235</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="92" Source="Action1" SourceLine="35" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="83" Source="Action1" SourceLine="31" >
<Disp><![CDATA[Tipo de Documento]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot open file: 'C:\Automatización\COTA\Capturas\Documento.png'.<BR>Line (37): &quot;Reporter.ReportEvent micPass, &quot;DNI&quot;, &quot;Funciona&quot;, &quot;C:\Automatización\COTA\Capturas\Documento.png&quot;&quot;. ]]></Details>
<Time><![CDATA[16/07/2014 - 11:33:56]]></Time>
<TimeTick>1405521236</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="93" status="Failed" Source="Action1" SourceLine="36" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Tipo de Documento]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:00]]></Time>
<TimeTick>1405521240</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[&Seleccionar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:00]]></Time>
<TimeTick>1405521240</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="96" Source="Action1" SourceLine="36" >
<Disp><![CDATA[&Seleccionar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="95" Source="Action1" SourceLine="36" >
<Disp><![CDATA[Tipo de Documento]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:01]]></Time>
<TimeTick>1405521241</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Número de Documento:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicDel&gt"]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:01]]></Time>
<TimeTick>1405521241</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="99" Source="Action1" SourceLine="39" >
<Disp><![CDATA[Número de Documento:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Número de Documento:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["12312312"]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:01]]></Time>
<TimeTick>1405521241</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="101" Source="Action1" SourceLine="40" >
<Disp><![CDATA[Número de Documento:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Número de Documento:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["CONSUMIDOR FINAL"]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:01]]></Time>
<TimeTick>1405521241</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="103" Source="Action1" SourceLine="42" >
<Disp><![CDATA[Número de Documento:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[&?_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:03]]></Time>
<TimeTick>1405521243</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="105" Source="Action1" SourceLine="44" >
<Disp><![CDATA[&?_2.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="98" Source="Action1" SourceLine="39" >
<Disp><![CDATA[Detalle de Cliente]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Tipo de Actividad]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:04]]></Time>
<TimeTick>1405521244</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Tipo de Actividad.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:04]]></Time>
<TimeTick>1405521244</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="108" Source="Action1" SourceLine="47" >
<Disp><![CDATA[Tipo de Actividad.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[ScrollBar.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[630]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:04]]></Time>
<TimeTick>1405521244</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="110" Source="Action1" SourceLine="48" >
<Disp><![CDATA[ScrollBar.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:06]]></Time>
<TimeTick>1405521246</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="112" Source="Action1" SourceLine="50" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[ScrollBar.PrevLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:07]]></Time>
<TimeTick>1405521247</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="114" Source="Action1" SourceLine="57" >
<Disp><![CDATA[ScrollBar.PrevLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:08]]></Time>
<TimeTick>1405521248</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="116" Source="Action1" SourceLine="50" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[ScrollBar.PrevLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:09]]></Time>
<TimeTick>1405521249</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="118" Source="Action1" SourceLine="57" >
<Disp><![CDATA[ScrollBar.PrevLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:09]]></Time>
<TimeTick>1405521249</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="120" Source="Action1" SourceLine="50" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[ScrollBar.PrevLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:10]]></Time>
<TimeTick>1405521250</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="122" Source="Action1" SourceLine="57" >
<Disp><![CDATA[ScrollBar.PrevLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:11]]></Time>
<TimeTick>1405521251</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="124" Source="Action1" SourceLine="50" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[ScrollBar.PrevLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[16/07/2014 - 11:34:12]]></Time>
<TimeTick>1405521252</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="126" Source="Action1" SourceLine="57" >