<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="ARBACNBK148"><DocLocation><![CDATA[C:\Automatización\COTA\Alta Cliente]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Alta Cliente]]></DName>
<Res><![CDATA[Res3]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" ShowDifference="False">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[PULIST.EXE]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[14/07/2014 - 12:17:51]]></Time>
<TimeTick>1405351071</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Cancel.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:17:51]]></Time>
<TimeTick>1405351071</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Cancel.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action1" SourceLine="4" >
<Disp><![CDATA[PULIST.EXE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Rul148q]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[14/07/2014 - 12:18:02]]></Time>
<TimeTick>1405351082</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[&No.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:18:02]]></Time>
<TimeTick>1405351082</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" Source="Action1" SourceLine="5" >
<Disp><![CDATA[&No.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="11" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Rul148q]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Bienvenido]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 12:18:06]]></Time>
<TimeTick>1405351086</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Bienvenido.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[237, 109]]></Details>
<Time><![CDATA[14/07/2014 - 12:18:06]]></Time>
<TimeTick>1405351086</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="Action1" SourceLine="6" >
<Disp><![CDATA[Bienvenido.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Usuario:.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[14/07/2014 - 12:18:06]]></Time>
<TimeTick>1405351086</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Usuario:.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Usuario:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["cgc014"]]></Details>
<Time><![CDATA[14/07/2014 - 12:18:06]]></Time>
<TimeTick>1405351086</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Usuario:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Password:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["BD2VWapm"]]></Details>
<Time><![CDATA[14/07/2014 - 12:18:06]]></Time>
<TimeTick>1405351086</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Action1" SourceLine="9" >
<Disp><![CDATA[Password:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Con&firmar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:18:07]]></Time>
<TimeTick>1405351087</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Con&firmar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Action1" SourceLine="6" >
<Disp><![CDATA[Bienvenido]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Menú Principal]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:33]]></Time>
<TimeTick>1405351173</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Menú Principal.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[238, 121]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:33]]></Time>
<TimeTick>1405351173</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Menú Principal.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[A&dministración de Clientes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:33]]></Time>
<TimeTick>1405351173</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="28" Source="Action1" SourceLine="13" >
<Disp><![CDATA[A&dministración de Clientes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Menú Principal]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Menú Principal Clientes]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:37]]></Time>
<TimeTick>1405351177</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Menú Principal Clientes.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[266, 141]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:37]]></Time>
<TimeTick>1405351177</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Menú Principal Clientes.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Alta de C&lientes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:37]]></Time>
<TimeTick>1405351177</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" Source="Action1" SourceLine="15" >
<Disp><![CDATA[Alta de C&lientes.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="30" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Menú Principal Clientes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:42]]></Time>
<TimeTick>1405351182</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente.Move]]></Obj>
<Details plainTxt="False" ><![CDATA[221, 132]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:42]]></Time>
<TimeTick>1405351182</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="36" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Detalle de Cliente.Move]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Tipo de Cliente:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["DUAL2"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:42]]></Time>
<TimeTick>1405351182</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="38" Source="Action1" SourceLine="18" >
<Disp><![CDATA[Tipo de Cliente:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Tipo de Cliente:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:42]]></Time>
<TimeTick>1405351182</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="40" Source="Action1" SourceLine="19" >
<Disp><![CDATA[Tipo de Cliente:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Apellido:.SetCaretPos]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 0]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:42]]></Time>
<TimeTick>1405351182</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="42" Source="Action1" SourceLine="21" >
<Disp><![CDATA[Apellido:.SetCaretPos]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Apellido:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Martinez"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:42]]></Time>
<TimeTick>1405351182</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="44" Source="Action1" SourceLine="22" >
<Disp><![CDATA[Apellido:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Apellido:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:43]]></Time>
<TimeTick>1405351183</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="46" Source="Action1" SourceLine="23" >
<Disp><![CDATA[Apellido:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Nombre:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Martin"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:43]]></Time>
<TimeTick>1405351183</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="48" Source="Action1" SourceLine="25" >
<Disp><![CDATA[Nombre:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Masc.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:43]]></Time>
<TimeTick>1405351183</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="50" Source="Action1" SourceLine="27" >
<Disp><![CDATA[Masc.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicHome&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:43]]></Time>
<TimeTick>1405351183</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" Source="Action1" SourceLine="30" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicShiftDwn&gt&lt__MicEnd&gt&lt__MicShiftUp&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:43]]></Time>
<TimeTick>1405351183</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" Source="Action1" SourceLine="31" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicBack&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:43]]></Time>
<TimeTick>1405351183</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="56" Source="Action1" SourceLine="32" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["25/06/1901"]]></Details>
<Time><![CDATA[14/07/2014 - 12:19:43]]></Time>
<TimeTick>1405351183</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="58" Source="Action1" SourceLine="33" >
<Disp><![CDATA[Fec Nacim/Inicio Activ:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[&?.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:04]]></Time>
<TimeTick>1405351204</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="61" status="Warning" Source="Action1" SourceLine="35" >
<Disp><![CDATA[&?.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "&?" (of class WinButton). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:04]]></Time>
<TimeTick>1405351204</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>window id = 48<br>Text = &?<br>Native Class = Button<br>]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:04]]></Time>
<TimeTick>1405351204</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="63" status="Warning" nType="Description" Source="Action1" SourceLine="35" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="62" status="Failed" nType="Run Error" Source="Action1" SourceLine="35" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="35" status="Failed" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Detalle de Cliente]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;&amp;?&quot; (of class WinButton). Verify that this object's properties match an object currently displayed in your application.<BR>Line (36): &quot;Window(&quot;Detalle de Cliente&quot;).WinButton(&quot;&amp;?&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:04]]></Time>
<TimeTick>1405351204</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="64" status="Failed" Source="Action1" SourceLine="35" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:29]]></Time>
<TimeTick>1405351229</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[&?.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:29]]></Time>
<TimeTick>1405351229</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="68" status="Warning" Source="Action1" SourceLine="35" >
<Disp><![CDATA[&?.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "&?" (of class WinButton). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:29]]></Time>
<TimeTick>1405351229</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[&?]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>window id = 48<br>Text = &?<br>Native Class = Button<br>]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:29]]></Time>
<TimeTick>1405351229</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="70" status="Warning" nType="Description" Source="Action1" SourceLine="35" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="69" status="Failed" nType="Run Error" Source="Action1" SourceLine="35" >
<Disp><![CDATA[&?]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="67" status="Failed" Source="Action1" SourceLine="35" >
<Disp><![CDATA[Detalle de Cliente]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;&amp;?&quot; (of class WinButton). Verify that this object's properties match an object currently displayed in your application.<BR>Line (36): &quot;Window(&quot;Detalle de Cliente&quot;).WinButton(&quot;&amp;?&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:29]]></Time>
<TimeTick>1405351229</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="71" status="Failed" Source="Action1" SourceLine="35" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Tipo de Documento]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:30]]></Time>
<TimeTick>1405351230</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:30]]></Time>
<TimeTick>1405351230</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="74" Source="Action1" SourceLine="35" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:30]]></Time>
<TimeTick>1405351230</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="76" Source="Action1" SourceLine="37" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:30]]></Time>
<TimeTick>1405351230</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="78" Source="Action1" SourceLine="38" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[ScrollBar.NextLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:30]]></Time>
<TimeTick>1405351230</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="80" Source="Action1" SourceLine="39" >
<Disp><![CDATA[ScrollBar.NextLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[210, 112]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:30]]></Time>
<TimeTick>1405351230</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="82" Source="Action1" SourceLine="40" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[&Seleccionar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:31]]></Time>
<TimeTick>1405351231</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="84" Source="Action1" SourceLine="41" >
<Disp><![CDATA[&Seleccionar.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="73" Source="Action1" SourceLine="35" >
<Disp><![CDATA[Tipo de Documento]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Detalle de Cliente]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:31]]></Time>
<TimeTick>1405351231</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Número de Documento:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicDel&gt"]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:31]]></Time>
<TimeTick>1405351231</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="87" Source="Action1" SourceLine="43" >
<Disp><![CDATA[Número de Documento:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Número de Documento:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["35139999"]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:31]]></Time>
<TimeTick>1405351231</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="89" Source="Action1" SourceLine="44" >
<Disp><![CDATA[Número de Documento:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Número de Documento:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["CONSUMIDOR FINAL"]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:31]]></Time>
<TimeTick>1405351231</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="91" Source="Action1" SourceLine="46" >
<Disp><![CDATA[Número de Documento:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[&?_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:52]]></Time>
<TimeTick>1405351252</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="94" status="Warning" Source="Action1" SourceLine="48" >
<Disp><![CDATA[&?_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[&?_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "&?_2" (of class WinButton). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:52]]></Time>
<TimeTick>1405351252</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[&?_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>window id = 52<br>Text = &?<br>Native Class = Button<br>]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:52]]></Time>
<TimeTick>1405351252</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="96" status="Warning" nType="Description" Source="Action1" SourceLine="48" >
<Disp><![CDATA[&?_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="95" status="Failed" nType="Run Error" Source="Action1" SourceLine="48" >
<Disp><![CDATA[&?_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="86" status="Failed" Source="Action1" SourceLine="43" >
<Disp><![CDATA[Detalle de Cliente]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;&amp;?_2&quot; (of class WinButton). Verify that this object's properties match an object currently displayed in your application.<BR>Line (49): &quot;Window(&quot;Detalle de Cliente&quot;).WinButton(&quot;&amp;?_2&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:52]]></Time>
<TimeTick>1405351252</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="97" status="Failed" Source="Action1" SourceLine="48" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Tipo de Actividad]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:55]]></Time>
<TimeTick>1405351255</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Tipo de Actividad.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:55]]></Time>
<TimeTick>1405351255</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="100" Source="Action1" SourceLine="48" >
<Disp><![CDATA[Tipo de Actividad.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[ScrollBar.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[630]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:55]]></Time>
<TimeTick>1405351255</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="102" Source="Action1" SourceLine="52" >
<Disp><![CDATA[ScrollBar.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:57]]></Time>
<TimeTick>1405351257</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="104" Source="Action1" SourceLine="54" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[ScrollBar.PrevLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:57]]></Time>
<TimeTick>1405351257</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="106" Source="Action1" SourceLine="60" >
<Disp><![CDATA[ScrollBar.PrevLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:59]]></Time>
<TimeTick>1405351259</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="108" Source="Action1" SourceLine="54" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[ScrollBar.PrevLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:59]]></Time>
<TimeTick>1405351259</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="110" Source="Action1" SourceLine="60" >
<Disp><![CDATA[ScrollBar.PrevLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[14/07/2014 - 12:20:59]]></Time>
<TimeTick>1405351259</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="112" Source="Action1" SourceLine="54" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[ScrollBar.PrevLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 12:21:00]]></Time>
<TimeTick>1405351260</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="114" Source="Action1" SourceLine="60" >
<Disp><![CDATA[ScrollBar.PrevLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[14/07/2014 - 12:21:00]]></Time>
<TimeTick>1405351260</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="116" Source="Action1" SourceLine="54" >
<Disp><![CDATA[AE Runtime.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[ScrollBar.PrevLine]]></Obj>
<Details plainTxt="False" ><![CDATA[1]]></Details>
<Time><![CDATA[14/07/2014 - 12:21:01]]></Time>
<TimeTick>1405351261</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="118" Source="Action1" SourceLine="60" >
<Disp><![CDATA[ScrollBar.PrevLine]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[AE Runtime.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[188, 29]]></Details>
<Time><![CDATA[14/07/2014 - 12:21:01]]></Time>
<TimeTick>1405351261</TimeTick>